### ISSUE TITLE
VB6 Compatibility?

### ISSUE THREAD

**Issue by Immortalin** [ocdtrekkie/HAController#5]

**Comment by ocdtrekkie** [comment]
None whatsoever. I wrote this against Visual Studio 2015 (and later upgraded to 2017), and it depends on .NET Framework 4.6.2. Sadly, I don't even have a copy of VB6 to play with some of my older programs.

**Comment by Immortalin** [comment]
Any planned support for .Net Core? On low-end devices, since VB6 isn't available, linux would be a good alternative.

**Comment by ocdtrekkie** [comment]
Eyeballing it but there's a lot of issues.

The biggest thing is that right now HAC has a WinForm-based UI, and that's entirely Windows-proprietary. The UI isn't super important, I primarily need a textbox to capture input in my car. .NET Core 3 adds support for WinForms, and I'll probably be able to move to .NET Core at that time, but it still won't work on Linux until the WinForm UI is gone.

Right now I run Windows 10 without a screen in my car, which is mostly silly: My app depends on UI being "visible" and "on top" for my car setup to work, and Windows 10 is not actually running in a headless fashion, so there is jankiness to that setup. Linux would be a far superior OS choice for that use case, so I'd love to go cross-platform.

The other thing I currently depend on a lot is that I use this heavily for music, by calling WindowsMedia APIs, and relying on Windows Media Player's library management features to catalog and retrieve my music, and a few other places I invoke EXEs or Windows Batch files to do things.

So cross-platform would be a lot of work, for now it requires full desktop Windows. It probably technically would work on Windows 7/8, but is only tested and used against Windows 10. FWIW, it only uses about 60 MB of RAM when it's running, but the lowest end machine I run it on has a Core i5 processor and 4 GB of RAM with an NVMe SSD. That's mostly just to ensure Windows 10 itself loads fast, since I boot it every time I get in the car.
